'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { categories, defaultAIOptions, type Content } from '@/lib/content';
type Media = { id: string; filename: string; title: string; alt: string; description: string; kind: string; language: string; active: number; created: string };
type Dashboard = { content: Content; inquiries: { id: number; name: string; email: string; category: string; message: string; created: string }[]; revisions: { id: number; created: string; editor: string }[]; media: Media[]; health: { database: boolean; aiConfigured: boolean } };
export default function Admin() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [lang, setLang] = useState('id'); const [tab, setTab] = useState('dashboard'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [raw, setRaw] = useState('');
  async function load(language = lang) {
    try { const response = await fetch(`/api/admin?lang=${language}`); if (response.status === 401) { setData(null); return; } if (!response.ok) throw new Error(); const next = await response.json(); setData(next); setRaw(JSON.stringify(next.content,null,2)); }
    catch { setMessage('Unable to load CMS. Check the server and retry.'); } finally { setLoading(false); }
  }
  useEffect(() => {
    let active = true;
    fetch('/api/admin?lang=id').then(async response => {
      if (response.status === 401) return null;
      if (!response.ok) throw new Error();
      return response.json();
    }).then(next => { if (active && next) { setData(next); setRaw(JSON.stringify(next.content, null, 2)); } }).catch(() => { if (active) setMessage('Unable to load CMS.'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);
  async function action(payload: Record<string, unknown>) {
    setBusy(true); setMessage('');
    try { const response = await fetch('/api/admin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ lang, ...payload }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); if (payload.action === 'logout') setData(null); else await load(); setMessage('Saved successfully.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Operation failed'); } finally { setBusy(false); }
  }
  function update(field: keyof Content, value: unknown) { if (data) setData({ ...data, content: { ...data.content, [field]: value } }); }
  async function mediaAction(method: string, body: Record<string, unknown>) {
    setBusy(true);
    try { const response = await fetch('/api/media', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(); await load(); setMessage('Media updated.'); }
    catch { setMessage('Media update failed.'); } finally { setBusy(false); }
  }
  if (loading) return <main className="admin"><p role="status">Loading CMS…</p></main>;
  if (!data) return <main className="admin"><Link href="/id">← Portfolio</Link><h1>Content studio</h1><p>Authorized editors only. Create the initial administrator using the documented setup command.</p><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: 'login', email: form.get('email'), password: form.get('password') }); }}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password" maxLength={200}/></label><button disabled={busy}>Sign in</button></form><p role="status">{message}</p></main>;
  const c = data.content;
  return <main className="admin"><header><div><a href={`/${lang}`}>← Portfolio</a><h1>Content studio</h1></div><button onClick={() => action({ action: 'logout' })}>Sign out</button></header><div className="inline"><label>Content language<select value={lang} onChange={event => { setLang(event.target.value); void load(event.target.value); }}><option value="id">Indonesia</option><option value="en">English</option></select></label><button disabled={busy} onClick={() => action({ action: 'save', content: c })}>Save draft</button><button disabled={busy} onClick={() => action({ action: 'publish', content: c })}>Publish</button><a href={`/${lang}?preview=1`} target="_blank" rel="noreferrer">Preview saved draft ↗</a></div><p role="status">{message}</p><nav className="admin-nav" aria-label="CMS sections">{['dashboard','profile',...categories,'settings','seo','media','revisions','advanced'].map(t => <button key={t} aria-pressed={tab===t} onClick={() => { setTab(t); if(t==='advanced') setRaw(JSON.stringify(c,null,2)); }}>{t}</button>)}</nav>
    {tab === 'dashboard' && <section><h2>Operations</h2><p>Database: connected · AI key: {data.health.aiConfigured ? 'configured' : 'not configured'} · AI publication: {c.settings.ai ? 'enabled' : 'disabled'}</p><p>{data.media.filter(m => m.kind==='cv' && m.active).length} active CV files · {data.revisions.length} recent revisions</p><h3>Recent inquiries</h3>{!data.inquiries.length && <p>No inquiries received.</p>}{data.inquiries.map(i => <article key={i.id}><h3>{i.name}</h3><p>{i.email} · {i.category} · {i.created}</p><p style={{whiteSpace:'pre-wrap'}}>{i.message}</p><a href={`mailto:${i.email}`}>Reply by email</a><button onClick={() => { if(confirm('Permanently delete this inquiry?')) void action({ action:'delete-inquiry',id:i.id }); }}>Delete</button></article>)}</section>}
    {tab === 'profile' && <section><h2>Profile & hero</h2>{(['name','role','headline','intro','location','email','whatsapp'] as const).map(field => <label key={field}>{field}<textarea rows={field==='intro'?4:2} value={c[field]} onChange={e => update(field,e.target.value)} /></label>)}</section>}
    {categories.includes(tab) && <section><h2>{tab}</h2><button onClick={() => update('entries',[...c.entries,{id:crypto.randomUUID(),category:tab,title:'',subtitle:'',body:'',visible:false,featured:false,order:c.entries.filter(e=>e.category===tab).length}])}>Add entry (hidden by default)</button>{c.entries.filter(e=>e.category===tab).map(entry => <article key={entry.id}>{(['title','subtitle','body','url','order'] as const).map(field => <label key={field}>{field}<input type={field==='order'?'number':'text'} min={0} value={entry[field] ?? ''} onChange={event => update('entries',c.entries.map(e=>e.id===entry.id?{...e,[field]:field==='order'?Number(event.target.value):event.target.value}:e))}/></label>)}{tab==='skills' && <label>Skill category<select value={entry.groupId || ''} onChange={event=>update('entries',c.entries.map(e=>e.id===entry.id?{...e,groupId:event.target.value || undefined}:e))}><option value="">Ungrouped</option>{c.entries.filter(e=>e.category==='skill-categories').map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label>}<label>Project image<select value={entry.mediaId || ""} onChange={event=>update("entries",c.entries.map(e=>e.id===entry.id?{...e,mediaId:event.target.value || undefined}:e))}><option value="">No image</option>{data.media.filter(m=>m.kind==="image" && m.active).map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><div className="inline">{(['visible','featured'] as const).map(field => <label key={field}>{field}<input type="checkbox" checked={entry[field]} onChange={event=>update('entries',c.entries.map(e=>e.id===entry.id?{...e,[field]:event.target.checked}:e))}/></label>)}<button onClick={()=>update('entries',c.entries.filter(e=>e.id!==entry.id))}>Remove from draft</button></div></article>)}</section>}
    {tab === 'settings' && <section><h2>Configuration & AI</h2><label>Typography<select value={c.appearance?.font || "sans"} onChange={e=>update("appearance",{font:e.target.value,spacing:c.appearance?.spacing || "relaxed"})}><option value="sans">Sans serif</option><option value="serif">Editorial serif</option></select></label><label>Spacing<select value={c.appearance?.spacing || "relaxed"} onChange={e=>update("appearance",{font:c.appearance?.font || "sans",spacing:e.target.value})}><option value="relaxed">Relaxed</option><option value="compact">Compact</option></select></label><p>API credentials are server environment variables, never browser-editable. Provider hosts must be explicitly allowed on the server. Model and instructions below are versioned with content.</p>{(['motion','ai','maintenance'] as const).map(field=><label className="inline" key={field}>{field}<input type="checkbox" checked={c.settings[field]} onChange={e=>update('settings',{...c.settings,[field]:e.target.checked})}/></label>)}<label>Default theme<select value={c.settings.theme} onChange={e=>update('settings',{...c.settings,theme:e.target.value})}><option>light</option><option>dark</option></select></label>{(['aiModel','aiBaseUrl','aiPrompt','whatsappMessage'] as const).map(field=><label key={field}>{field}<textarea rows={field==='aiPrompt'?6:2} value={c.settings[field]} onChange={e=>update('settings',{...c.settings,[field]:e.target.value})}/></label>)}<p>AI is optional. Enable only after configuring a provider, reviewing its privacy terms, and validating answers.</p></section>}
    {tab === 'settings' && <section><h3>AI response controls</h3>{(['temperature','maxTokens','timeoutMs'] as const).map(field => <label key={field}>{field}<input type="number" step={field==='temperature'?0.1:1} value={(c.aiOptions || defaultAIOptions)[field]} onChange={e=>update('aiOptions',{...(c.aiOptions || defaultAIOptions),[field]:Number(e.target.value)})}/></label>)}<label>Welcome message<input value={c.aiOptions?.welcome || ''} onChange={e=>update('aiOptions',{...(c.aiOptions || defaultAIOptions),welcome:e.target.value})}/></label><label>Suggested questions (one per line, maximum six)<textarea value={(c.aiOptions?.suggestions || []).join('\n')} onChange={e=>update('aiOptions',{...(c.aiOptions || defaultAIOptions),suggestions:e.target.value.split('\n').filter(Boolean)})}/></label><button disabled={busy} onClick={async()=>{setBusy(true);try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lang,message:lang==='en'?'What services are available?':'Layanan apa yang tersedia?'})});const result=await response.json();setMessage(result.answer || result.error);}catch{setMessage('Connection test failed');}finally{setBusy(false);}}}>Test published AI connection</button><p>The test uses published settings. Save and publish configuration first.</p></section>}
    {tab==='seo' && <section><h2>Search metadata</h2><label className="inline">Hide from search engines<input type="checkbox" checked={c.seo.noindex || false} onChange={e=>update("seo",{...c.seo,noindex:e.target.checked})}/></label><label>Open Graph image<select value={c.seo.imageId || ""} onChange={e=>update("seo",{...c.seo,imageId:e.target.value || undefined})}><option value="">No image</option>{data.media.filter(m=>m.kind==="image" && m.active).map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>{(['title','description'] as const).map(field=><label key={field}>{field}<textarea value={c.seo[field]} onChange={e=>update('seo',{...c.seo,[field]:e.target.value})}/></label>)}</section>}
    {tab==='media' && <section><h2>Media & CV versions</h2><p>PDF / JPEG / PNG / WebP, maximum 5 MB. Uploads are private until activated. Upload a replacement before deactivating or deleting an old version.</p><form onSubmit={async event=>{event.preventDefault();setBusy(true);const form=event.currentTarget;try{const response=await fetch('/api/media',{method:'POST',body:new FormData(form)});if(!response.ok)throw new Error();await load();form.reset();setMessage('Uploaded. Review metadata, then activate.');}catch{setMessage('Upload failed. Check file format and size.');}finally{setBusy(false);}}}><label>File<input type="file" name="file" accept="application/pdf,image/png,image/jpeg,image/webp" required/></label><label>Title<input name="title" required maxLength={200}/></label><label>Alternative text<input name="alt" maxLength={500}/></label><label>Language<select name="language"><option value="id">Indonesia</option><option value="en">English</option></select></label><button disabled={busy}>Upload</button></form><label>Search media<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{data.media.filter(m=>`${m.title} ${m.kind} ${m.language}`.toLowerCase().includes(search.toLowerCase())).map(m=><article key={m.id}><a href={`/api/media?id=${m.id}`} target="_blank" rel="noreferrer">{m.filename} ↗</a><p>{m.kind} · {m.language} · {m.created} · {m.active?'active':'inactive'}</p><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void mediaAction('PATCH',{id:m.id,title:form.get('title'),alt:form.get('alt'),description:form.get('description'),active:form.get('active')==='on'});}}><label>Title<input name="title" defaultValue={m.title}/></label><label>Alt text<input name="alt" defaultValue={m.alt}/></label><label>Description<input name="description" defaultValue={m.description}/></label><label className="inline">Active<input type="checkbox" name="active" defaultChecked={!!m.active}/></label><button disabled={busy}>Save metadata</button><button type="button" disabled={busy} onClick={()=>{if(confirm('Delete this file permanently?'))void mediaAction('DELETE',{id:m.id});}}>Delete</button></form></article>)}</section>}
    {tab==='revisions' && <section><h2>Revision history</h2><p>Restoring changes the draft only. Preview before publishing.</p>{data.revisions.map(r=><article key={r.id}><span>#{r.id} · {r.created} · {r.editor}</span><button onClick={()=>action({action:'restore',id:r.id})}>Restore to draft</button></article>)}</section>}
    {tab==='advanced' && <section><h2>Structured content editor</h2><p>For bulk editing and export. Apply to draft, then save. Invalid content is rejected by the server.</p><textarea className="code" aria-label="Content JSON" value={raw} onChange={e=>setRaw(e.target.value)}/><button onClick={()=>{try{const parsed=JSON.parse(raw);void action({action:'save',content:parsed});}catch{setMessage('Invalid JSON');}}}>Validate & save JSON draft</button></section>}
  </main>;
}
