import { test, expect } from '@playwright/test';
import { randomBytes, scryptSync } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';
import sharp from 'sharp';
import { unlinkSync, existsSync } from 'node:fs';
const email=`media-${randomBytes(8).toString('hex')}@localhost.test`;
const password=randomBytes(24).toString('hex');let adminId:number;let mediaId='';
test.beforeAll(async({request})=>{expect((await request.get('/id')).status()).toBe(200);const db=new DatabaseSync(path.join(process.env.DATA_DIR||'data','portfolio.sqlite'));const salt=randomBytes(16).toString('hex');adminId=Number(db.prepare('INSERT INTO admins(email,password) VALUES (?,?)').run(email,`${salt}:${scryptSync(password,salt,64).toString('hex')}`).lastInsertRowid);db.close();});
test.afterAll(()=>{const db=new DatabaseSync(path.join(process.env.DATA_DIR||'data','portfolio.sqlite'));db.prepare('DELETE FROM sessions WHERE admin=?').run(adminId);db.prepare('DELETE FROM admins WHERE id=?').run(adminId);if(mediaId){db.prepare('DELETE FROM media WHERE id=?').run(mediaId);const file=path.join(process.env.DATA_DIR||'data','uploads',mediaId);if(existsSync(file))unlinkSync(file);}db.close();});
test('media upload, private preview, activation and deletion',async({request,playwright,baseURL})=>{
  const origin=baseURL!;
  const login=await request.post('/api/admin',{headers:{Origin:origin},data:{action:'login',email,password}});
  expect(login.status()).toBe(200);
  const png=await sharp({create:{width:8,height:8,channels:3,background:'#ffffff'}}).png().toBuffer();
  const malformed=await request.post('/api/media',{headers:{Origin:origin},multipart:{file:{name:'broken.png',mimeType:'image/png',buffer:png.subarray(0,16)}}});
  expect(malformed.status()).toBe(400);
  const upload=await request.post('/api/media',{headers:{Origin:origin},multipart:{file:{name:'qa.png',mimeType:'image/png',buffer:png},title:'QA media',alt:'QA image',language:'id'}});
  expect(upload.status()).toBe(200);mediaId=(await upload.json()).id;
  const anonymous=await playwright.request.newContext({baseURL});
  expect((await anonymous.get(`/api/media?id=${mediaId}`)).status()).toBe(404);
  expect((await request.get(`/api/media?id=${mediaId}`)).status()).toBe(200);
  expect((await request.patch('/api/media',{headers:{Origin:origin},data:{id:mediaId,active:true,title:'QA media',alt:'QA image',description:'Integration test'}})).status()).toBe(200);
  const published=await anonymous.get(`/api/media?id=${mediaId}`);
  expect(published.status()).toBe(200);
  expect(published.headers()['content-type']).toBe('image/webp');
  const decoded=await sharp(await published.body()).metadata();
  expect(decoded.width).toBe(8);
  expect(decoded.exif).toBeUndefined();
  expect((await request.delete('/api/media',{headers:{Origin:origin},data:{id:mediaId}})).status()).toBe(200);
  expect((await anonymous.get(`/api/media?id=${mediaId}`)).status()).toBe(404);
  await anonymous.dispose();
});
test('disabled AI and invalid contact degrade safely',async({request,baseURL})=>{
  const headers={Origin:baseURL!};
  expect((await request.post('/api/chat',{headers,data:{lang:'id',message:'Apa layanan Anda?'}})).status()).toBe(503);
  expect((await request.post('/api/chat',{headers,data:{lang:'invalid',message:''}})).status()).toBe(400);
  expect((await request.post('/api/contact',{headers,data:{name:'A',email:'invalid',category:'consultation',message:'short',website:'',lang:'id'}})).status()).toBe(400);
});
