import { test, expect } from '@playwright/test';
import { randomBytes, scryptSync } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';
const email = `qa-${randomBytes(6).toString('hex')}@localhost.test`;
const password = randomBytes(24).toString('hex');
let adminId: number;
test.beforeAll(() => {
  const db = new DatabaseSync(path.join(process.env.DATA_DIR || 'data', 'portfolio.sqlite'));
  const salt = randomBytes(16).toString('hex');
  adminId = Number(db.prepare('INSERT INTO admins (email,password) VALUES (?,?)').run(email, `${salt}:${scryptSync(password,salt,64).toString('hex')}`).lastInsertRowid);
  db.close();
});
test.afterAll(() => {
  const db = new DatabaseSync(path.join(process.env.DATA_DIR || 'data', 'portfolio.sqlite'));
  db.prepare('DELETE FROM sessions WHERE admin=?').run(adminId);
  db.prepare('DELETE FROM admins WHERE id=?').run(adminId);
  db.prepare("DELETE FROM inquiries WHERE email='portfolio-qa@localhost.test'").run();
  db.close();
});
test('public experience, language, theme, mobile and contact', async ({ page }) => {
  await page.goto('/id');
  await expect(page.getByRole('heading', {level:1})).toContainText('Teknologi yang bekerja');
  await page.getByRole('button',{name:'Jelajahi koneksinya'}).click();
  await expect(page.getByRole('button',{name:'Tutup eksplorasi'})).toBeVisible();
  await page.getByRole('button',{name:'Cloud computing',exact:true}).click();
  await expect(page.locator('.explorer-detail')).toContainText('Virtualisasi');
  await page.getByRole('button',{name:'Ganti tema warna'}).click();
  await expect(page.locator('.portfolio')).toHaveClass(/dark/);
  await page.getByRole('link',{name:'English',exact:true}).click();
  await expect(page.getByRole('heading',{level:1})).toContainText('Technology that works');
  await page.getByRole('button',{name:'Toggle color theme'}).click();
  await expect(page.locator('.portfolio')).not.toHaveClass(/dark/);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByLabel('Your name', {exact:true}).fill('Portfolio QA');
  await page.getByLabel('Email address', {exact:true}).fill('portfolio-qa@localhost.test');
  await page.getByLabel('What can I help with?', {exact:true}).fill('Automated QA inquiry. Safe to delete.');
  await page.getByRole('button',{name:'Send inquiry'}).click();
  await expect(page.getByRole('status')).toContainText('Message received');
});
test('API rejects unauthorized access and invalid submissions',async({request})=>{
  expect((await request.get('/api/admin')).status()).toBe(401);
  expect((await request.post('/api/admin',{data:{action:'publish'}})).status()).toBe(403);
  expect((await request.post('/api/contact',{data:{}})).status()).toBe(403);
  const response=await request.get('/cv?lang=id');
  expect(response.status()).toBe(200);expect(response.headers()['content-type']).toBe('application/pdf');
  expect((await request.get('/cv?lang=en')).status()).toBe(404);
  expect((await request.get('/not-a-page')).status()).toBe(404);
});
test('CMS login, draft, publish, restore, inquiry and logout',async({page})=>{
  await page.goto('/admin');
  await page.getByLabel('Email',{exact:true}).fill(email);
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Operations'})).toBeVisible();
  await page.getByRole('button',{name:'profile',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Profile & hero'})).toBeVisible();
  const role=page.getByLabel(/^role/);const original=await role.inputValue();
  await role.fill(original);
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  await page.getByRole('button',{name:'Publish',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  await page.getByRole('button',{name:'revisions',exact:true}).click();
  await page.getByRole('button',{name:'Restore to draft',exact:true}).first().click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();
});
