import { test, expect } from '@playwright/test';
import { randomBytes, scryptSync } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';
const email = `qa-${randomBytes(6).toString('hex')}@localhost.test`;
const password = randomBytes(24).toString('hex');
let adminId: number;
test.beforeAll(async ({ request }) => {
  expect((await request.get('/id')).status()).toBe(200);
  const db = new DatabaseSync(path.join(process.env.DATA_DIR || 'data', 'portfolio.sqlite'));
  const salt = randomBytes(16).toString('hex');
  adminId = Number(db.prepare('INSERT INTO admins (email,password) VALUES (?,?)').run(email, `${salt}:${scryptSync(password,salt,64).toString('hex')}`).lastInsertRowid);
  db.close();
});
test.afterAll(() => {
  const db = new DatabaseSync(path.join(process.env.DATA_DIR || 'data', 'portfolio.sqlite'));
  db.prepare('DELETE FROM sessions WHERE admin=?').run(adminId);
  db.prepare('DELETE FROM admins WHERE id=?').run(adminId);
  db.prepare("DELETE FROM inquiries WHERE email='portfolio-qa@localhost.test'").run();
  db.close();
});
test('public experience, language, theme, mobile and contact', async ({ page }) => {
  await page.goto('/id');
  await expect(page.getByRole('heading', {level:1})).toContainText('Teknologi yang bekerja');
  const structured = await page.locator('script[type="application/ld+json"]').textContent();
  expect(JSON.parse(structured || '{}')['@type']).toBe('Person');
  await page.getByRole('button',{name:'Jelajahi koneksinya'}).click();
  await expect(page.getByRole('button',{name:'Tutup eksplorasi'})).toBeVisible();
  await page.getByRole('button',{name:'Cloud computing',exact:true}).click();
  await expect(page.locator('.explorer-detail')).toContainText('Virtualisasi');
  await page.getByRole('button',{name:'Ganti tema warna'}).click();
  await expect(page.locator('.portfolio')).toHaveClass(/dark/);
  await page.getByRole('link',{name:'English',exact:true}).click();
  await expect(page.getByRole('heading',{level:1})).toContainText('Technology that works');
  await page.getByRole('button',{name:'Toggle color theme'}).click();
  await expect(page.locator('.portfolio')).not.toHaveClass(/dark/);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByLabel('Your name', {exact:true}).fill('Portfolio QA');
  await page.getByLabel('Email address', {exact:true}).fill('portfolio-qa@localhost.test');
  await page.getByLabel('What can I help with?', {exact:true}).fill('Automated QA inquiry. Safe to delete.');
  await page.getByRole('button',{name:'Send inquiry'}).click();
  await expect(page.getByRole('status')).toContainText('Message received');
});
test('core portfolio remains readable without JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false });
  try {
    const page = await context.newPage();
    await page.goto(`${process.env.TEST_BASE_URL || 'http://localhost:3000'}/id`);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    await expect(page.locator('#services')).toBeVisible();
    await expect(page.locator('#experience')).toBeVisible();
    await expect(page.getByRole('link', { name: 'WhatsApp', exact: false })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Unduh CV', exact: false })).toBeVisible();
  } finally { await context.close(); }
});
test('keyboard navigation and reduced motion remain usable', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/id');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Langsung ke konten' })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page).toHaveURL(/#main$/);
  await page.setViewportSize({ width: 320, height: 700 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('button', { name: 'Ganti tema warna' })).toBeVisible();
});
test('API rejects unauthorized access and invalid submissions',async({request})=>{
  expect((await request.get('/api/admin')).status()).toBe(401);
  expect((await request.post('/api/admin',{data:{action:'publish'}})).status()).toBe(403);
  expect((await request.post('/api/contact',{data:{}})).status()).toBe(403);
  const response=await request.get('/cv?lang=id');
  expect(response.status()).toBe(200);expect(response.headers()['content-type']).toBe('application/pdf');
  expect((await request.get('/cv?lang=en')).status()).toBe(404);
  expect((await request.get('/not-a-page')).status()).toBe(404);
  const firstPage = await request.get('/id');
  const secondPage = await request.get('/id');
  const policy = firstPage.headers()['content-security-policy'];
  expect(policy).toContain("'nonce-");
  expect(policy.split('script-src')[1].split(';')[0]).not.toContain('unsafe-inline');
  expect(policy).not.toBe(secondPage.headers()['content-security-policy']);
  const preview = await request.get('/id?preview=1');
  expect(await preview.text()).toContain('name="robots" content="noindex, nofollow"');
});
test('CMS login, draft, publish, restore, inquiry and logout',async({page})=>{
  await page.goto('/admin');
  await page.getByLabel('Email',{exact:true}).fill(email);
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Operations'})).toBeVisible();
  await page.getByRole('button',{name:'profile',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Profile & hero'})).toBeVisible();
  const role=page.getByLabel(/^role/);const original=await role.inputValue();
  await role.fill(original);
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  await page.getByRole('button',{name:'Publish',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  await page.getByRole('button',{name:'skills',exact:true}).click();
  await expect(page.getByLabel(/^Skill category/).first()).toBeVisible();
  await page.getByRole('button',{name:'settings',exact:true}).click();
  await expect(page.getByLabel(/^Typography/)).toBeVisible();
  await page.getByLabel(/^Visual style/).selectOption('cyberpunk');
  await page.getByLabel(/^Typography/).selectOption('serif');
  await page.getByLabel(/^Spacing/).selectOption('compact');
  await expect(page.getByLabel('safeMode', { exact: true })).toBeVisible();
  await expect(page.getByLabel('temperature',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Test published AI connection'}).click();
  await expect(page.getByRole('status')).toContainText('Asisten belum tersedia');
  await page.getByRole('button',{name:'seo',exact:true}).click();
  await expect(page.getByLabel(/^Open Graph image/)).toBeVisible();
  await page.getByRole('button',{name:'settings',exact:true}).click();
  await page.getByLabel('safeMode',{exact:true}).check();
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  const previewPage = await page.context().newPage();
  await previewPage.goto('/id?preview=1');
  await expect(previewPage.locator('.portfolio')).toHaveClass(/no-motion/);
  await expect(previewPage.locator('.portfolio')).toHaveClass(/style-cyberpunk/);
  await expect(previewPage.locator('.hero-network')).not.toHaveClass(/flowing/);
  await expect(previewPage.locator('.motion-control')).toHaveCount(0);
  await expect(previewPage.getByRole('button',{name:'Jelajahi koneksinya'})).toHaveCount(0);
  await expect(previewPage.locator('#services')).toBeVisible();
  await expect(previewPage.locator('#contact')).toBeVisible();
  await previewPage.close();
  await page.getByRole('button',{name:'revisions',exact:true}).click();
  await page.getByRole('button',{name:'Restore to draft',exact:true}).first().click();
  await expect(page.getByRole('status')).toHaveText('Saved successfully.');
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();
});
