'use client';
import { useEffect, useState, useSyncExternalStore } from 'react';
import Link from 'next/link';
const subscribeTheme = (callback: () => void) => { window.addEventListener('storage', callback); return () => window.removeEventListener('storage', callback); };
const readTheme = () => { try { return localStorage.getItem('theme'); } catch { return null; } };
const serverTheme = () => null;
import type { Content, Language } from '@/lib/content';

export default function Portfolio({ content: c, lang, preview }: { content: Content; lang: Language; preview: boolean }) {
  const en = lang === 'en';
  const savedTheme = useSyncExternalStore(subscribeTheme, readTheme, serverTheme);
  const [themeOverride, setDark] = useState<boolean | null>(null);
  const dark = themeOverride ?? (savedTheme ? savedTheme === 'dark' : c.settings.theme === 'dark');
  const [selected, setSelected] = useState('network');
  const [explore, setExplore] = useState(false);
  const [chat, setChat] = useState(false);
  const [answer, setAnswer] = useState('');
  const [chatBusy, setChatBusy] = useState(false);
  const [formState, setFormState] = useState('');
  const [sending, setSending] = useState(false);
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  const entries = (category: string) => c.entries.filter(e => e.category === category && e.visible).sort((a,b) => a.order - b.order);
  const services = entries('services');
  const active = services.find(s => s.id === selected) || services[0];
  const whatsapp = `https://wa.me/${c.whatsapp}?text=${encodeURIComponent(c.settings.whatsappMessage)}`;
  const labels = en ? { services: 'Capabilities', experience: 'Experience', contact: 'Let’s talk', explore: 'Explore the connections', cv: 'Download CV', about: 'A practical approach', send: 'Send inquiry', name: 'Your name', email: 'Email address', message: 'What can I help with?', category: 'Service', note: 'Your message is stored privately to respond to your inquiry. No marketing.', success: 'Message received. Thank you — your inquiry has been saved.', failure: 'Could not send. Please try again or contact me on WhatsApp.' } : { services: 'Keahlian', experience: 'Pengalaman', contact: 'Mari diskusi', explore: 'Jelajahi koneksinya', cv: 'Unduh CV', about: 'Pendekatan yang praktis', send: 'Kirim pesan', name: 'Nama Anda', email: 'Alamat email', message: 'Apa yang bisa saya bantu?', category: 'Layanan', note: 'Pesan disimpan secara privat untuk menanggapi kebutuhan Anda. Tanpa pemasaran.', success: 'Pesan diterima. Terima kasih — kebutuhan Anda telah tersimpan.', failure: 'Pesan gagal dikirim. Coba lagi atau hubungi melalui WhatsApp.' };
  async function submitContact(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSending(true); setFormState(''); const form = event.currentTarget;
    const data = Object.fromEntries(new FormData(form));
    try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...data, lang }) }); if (!response.ok) throw new Error(); setFormState(labels.success); form.reset(); }
    catch { setFormState(labels.failure); } finally { setSending(false); }
  }
  async function submitChat(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setChatBusy(true); const data = new FormData(event.currentTarget);
    try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: data.get('message'), lang }) }); const result = await response.json(); setAnswer(result.answer || result.error); }
    catch { setAnswer(en ? 'Connection unavailable. Please use WhatsApp.' : 'Koneksi tidak tersedia. Silakan gunakan WhatsApp.'); } finally { setChatBusy(false); }
  }
  return <div className={`portfolio ${dark ? 'dark' : ''} ${c.settings.motion ? '' : 'no-motion'}`}>
    <a className="skip" href="#main">{en ? 'Skip to content' : 'Langsung ke konten'}</a>
    {preview && <div className="preview">DRAFT PREVIEW — <Link href="/admin">CMS</Link></div>}
    <header className="header"><a className="brand" href={`/${lang}`} aria-label={c.name}>ay<span className="brand-dot">.</span></a><nav aria-label={en ? 'Main navigation' : 'Navigasi utama'}><a href="#services">{labels.services}</a><a href="#experience">{labels.experience}</a><a className="nav-contact" href="#contact">{labels.contact} <span>↗</span></a></nav><div className="controls"><a href={`/${en ? 'id' : 'en'}`} hrefLang={en ? 'id' : 'en'} aria-label={en ? 'Bahasa Indonesia' : 'English'}>{en ? 'ID' : 'EN'}</a><button aria-label={en ? 'Toggle color theme' : 'Ganti tema warna'} onClick={() => { setDark(!dark); try { localStorage.setItem('theme', !dark ? 'dark' : 'light'); } catch {} }}>{dark ? '☀' : '◐'}</button></div></header>
    <main id="main">
      {c.settings.maintenance && <p className="notice">{en ? 'Updates are in progress. Contact remains available.' : 'Pembaruan sedang berlangsung. Kontak tetap tersedia.'}</p>}
      <section className="hero" aria-labelledby="hero-title"><div className="hero-meta"><span><i className="status-dot" />{c.location}</span><span>01 / {en ? 'INTRODUCTION' : 'PERKENALAN'}</span></div><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">{c.name} <span>— {c.role}</span></p><h1 id="hero-title">{c.headline.split('\n').map((line,i) => <span key={i} className={i ? 'muted-title' : ''}>{line}</span>)}</h1><p className="intro">{c.intro}</p><div className="hero-actions"><a className="button primary" href="#contact">{labels.contact} <span>↗</span></a><a className="text-link" href={`/cv?lang=${lang}`}>{labels.cv} <span>↓</span></a></div><p className="cv-note">{en ? 'Original CV: Indonesian · English version when available' : 'CV asli berbahasa Indonesia'}</p></div>
      <div className="infrastructure" aria-label={en ? 'Connected technical infrastructure' : 'Infrastruktur teknis yang terhubung'}><div className="diagram-top"><span>AY / SYSTEM MAP</span><span className="diagram-status">● CONNECTED</span></div><svg viewBox="0 0 400 370" role="img" aria-label={en ? 'People connected to networks, cloud, and digital tools' : 'Manusia terhubung dengan jaringan, cloud, dan perangkat digital'}><defs><pattern id="dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="currentColor" opacity=".14" /></pattern></defs><rect width="400" height="370" fill="url(#dots)"/><g className="connections" fill="none" stroke="currentColor" strokeWidth="1"><path d="M200 180 L80 110 L80 260 L200 320 L320 250 L320 110 Z"/><path d="M80 110 L200 45 L320 110 M200 45 V180 L320 250 M80 260 L200 180 V320 M80 110 L320 250 M320 110 L80 260"/></g><g className="node"><circle cx="200" cy="180" r="48"/><text x="200" y="174" textAnchor="middle" className="node-symbol">ay.</text><text x="200" y="198" textAnchor="middle">HUMAN FIRST</text></g>{[[80,110,'NETWORK'],[200,45,'CLOUD'],[320,110,'WEB'],[80,260,'HARDWARE'],[320,250,'AUTOMATION'],[200,320,'SUPPORT']].map(([x,y,label]) => <g key={label} className="satellite"><circle cx={x} cy={y} r="5"/><text x={x} y={Number(y)+22} textAnchor="middle">{label}</text></g>)}</svg><div className="diagram-bottom"><span>TECHNOLOGY → PEOPLE</span><span>02°  /  06 NODES</span></div></div></div><div className="hero-footer"><span>{en ? 'Practical solutions. Connected thinking.' : 'Solusi praktis. Cara berpikir yang terhubung.'}</span><a href="#services">{en ? 'Scroll to discover' : 'Kenali lebih dekat'} ↓</a></div></section>
      <section id="services" className="section services"><div className="section-heading"><p className="eyebrow">02 / {en ? 'CAPABILITIES' : 'KEAHLIAN'}</p><h2>{en ? 'Different needs.\nOne connected approach.' : 'Beragam kebutuhan.\nSatu pendekatan terhubung.'}</h2><p>{en ? 'The right tools matter. Understanding the problem matters more.' : 'Perangkat yang tepat itu penting. Memahami persoalannya lebih penting.'}</p></div><div className="service-list">{services.map((service,i) => <details key={service.id}><summary><span className="index">{String(i+1).padStart(2,'0')}</span><h3>{service.title}</h3><span className="plus">+</span></summary><div className="service-body"><p>{service.body}</p><a href={`${whatsapp}%20${encodeURIComponent(service.title)}`}>{en ? 'Discuss this service' : 'Diskusikan layanan ini'} ↗</a></div></details>)}</div></section>
      <section className="explore-section"><div><p className="eyebrow">{en ? 'THE BIGGER PICTURE' : 'GAMBARAN BESARNYA'}</p><h2>{en ? 'Nothing works\nin isolation.' : 'Tidak ada yang bekerja\nsendirian.'}</h2><p>{en ? 'A useful system connects tools, processes, and people.' : 'Sistem yang berguna menghubungkan perangkat, proses, dan manusia.'}</p></div><button className="button outline" aria-expanded={explore} onClick={() => setExplore(!explore)}>{explore ? (en ? 'Close exploration' : 'Tutup eksplorasi') : labels.explore} {explore ? '−' : '↗'}</button>{explore && <div className="explorer"><div className="node-options" aria-label={labels.services}>{services.map(s => <button key={s.id} aria-pressed={active?.id === s.id} onClick={() => setSelected(s.id)}>{s.title}</button>)}</div><div className="explorer-detail" aria-live="polite"><p className="eyebrow">{en ? 'NEED → SYSTEM → PEOPLE' : 'KEBUTUHAN → SISTEM → MANUSIA'}</p><h3>{active?.title}</h3><p>{active?.body}</p><a href="#contact">{labels.contact} ↗</a></div></div>}</section>
      <section id="experience" className="section experience"><div className="section-heading"><p className="eyebrow">03 / {en ? 'EXPERIENCE' : 'PENGALAMAN'}</p><h2>{en ? 'Built through\nreal work.' : 'Tumbuh dari\npengalaman nyata.'}</h2><p>{en ? 'Across infrastructure, education, design, and hands-on support. Source: supplied 2025 CV; current employment has not been reconfirmed.' : 'Lintas infrastruktur, pendidikan, desain, dan dukungan langsung. Sumber: CV 2025; status pekerjaan terkini belum dikonfirmasi ulang.'}</p></div><div className="timeline">{entries('experience').map((e,i) => <article key={e.id}><span className="index">{String(i+1).padStart(2,'0')}</span><div><p className="job-meta">{e.subtitle}</p><h3>{e.title}</h3><p>{e.body}</p></div></article>)}</div></section>
      <section className="section knowledge"><div><p className="eyebrow">04 / {en ? 'FOUNDATIONS' : 'LANDASAN'}</p><h2>{labels.about}</h2>{entries('education').map(e => <article key={e.id}><h3>{e.title}</h3><p>{e.subtitle}</p><p>{e.body}</p></article>)}</div><div className="skills">{entries('skills').map(e => <span key={e.id}>{e.title}</span>)}</div></section>
      {entries('projects').length > 0 && <section className="section"><h2>{en ? 'Selected work' : 'Karya pilihan'}</h2>{entries('projects').map(e => <article key={e.id}><h3>{e.title}</h3><p>{e.subtitle}</p><p>{e.body}</p></article>)}</section>}
      {entries('faq').length > 0 && <section className="section"><h2>FAQ</h2>{entries('faq').map(e => <details key={e.id}><summary>{e.title}</summary><p>{e.body}</p></details>)}</section>}
      <section id="contact" className="section contact"><div><p className="eyebrow">05 / {en ? 'LET’S CONNECT' : 'MARI TERHUBUNG'}</p><h2>{en ? 'A good solution\nstarts with a conversation.' : 'Solusi yang baik\ndimulai dari percakapan.'}</h2><p>{en ? 'Tell me what you’re working on, or what isn’t working.' : 'Ceritakan apa yang sedang Anda kerjakan, atau apa yang belum berjalan.'}</p><a className="contact-email" href={`mailto:${c.email}`}>{c.email} ↗</a><a className="text-link" href={whatsapp}>WhatsApp ↗</a><p className="small">{c.location}</p></div><form onSubmit={submitContact}><label>{labels.name}<input name="name" required minLength={2} maxLength={100} autoComplete="name" /></label><label>{labels.email}<input name="email" type="email" required maxLength={200} autoComplete="email" /></label><label>{labels.category}<select name="category"><option value="consultation">{en ? 'Consultation' : 'Konsultasi'}</option>{services.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}<option value="other">{en ? 'Other' : 'Lainnya'}</option></select></label><label>{labels.message}<textarea name="message" required minLength={10} maxLength={4000} rows={4}/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><p className="small">{labels.note}</p><button className="button primary" disabled={sending}>{sending ? (en ? 'Sending…' : 'Mengirim…') : labels.send} ↗</button><p role="status">{formState}</p></form></section>
    </main><footer><a className="brand" href={`/${lang}`}>ay.</a><p>© {new Date().getFullYear()} {c.name}</p><span>{en ? 'Thoughtfully connected.' : 'Terhubung dengan tujuan.'}</span><a href="#main">↑ {en ? 'Back to top' : 'Kembali ke atas'}</a></footer>
    {c.settings.ai && <><button className="chat-toggle" onClick={() => setChat(!chat)} aria-expanded={chat}>{en ? 'Ask the assistant' : 'Tanya asisten'} {chat ? '−' : '+'}</button>{chat && <aside className="chat-panel" aria-label={en ? 'AI portfolio assistant' : 'Asisten portofolio AI'}><h3>{en ? 'Portfolio assistant' : 'Asisten portofolio'}</h3><p className="small">{en ? 'AI assistant, not Ashabul. Messages are sent to an external AI provider. Do not share sensitive information.' : 'Asisten AI, bukan Ashabul. Pesan dikirim ke penyedia AI eksternal. Jangan bagikan informasi sensitif.'}</p><p className="chat-answer" role="status">{answer}</p><form onSubmit={submitChat}><label>{en ? 'Your question' : 'Pertanyaan Anda'}<input name="message" required maxLength={1000}/></label><button className="button primary" disabled={chatBusy}>{chatBusy ? '…' : en ? 'Ask' : 'Tanyakan'} ↗</button></form></aside>}</>}
  </div>;
}
